production: &production
  facebook:
    key: <%= ENV['FACEBOOK_KEY'] %>
    secret: <%= ENV['FACEBOOK_SECRET'] %>
  google:
    key: <%= ENV['GOOGLE_KEY'] %>
    secret: <%= ENV['GOOGLE_SECRET'] %>
  twitter:
    key: <%= ENV['TWITTER_KEY'] %>
    secret: <%= ENV['TWITTER_SECRET'] %>

development: &development
  <<: *production
  facebook:
    key: <%= ENV['FACEBOOK_KEY'] %>
    secret: <%= ENV['FACEBOOK_SECRET'] %>
  google:
    key: <%= ENV['GOOGLE_KEY'] %>
    secret: <%= ENV['GOOGLE_SECRET'] %>
  twitter:
    key: <%= ENV['TWITTER_KEY'] %>
    secret: <%= ENV['TWITTER_SECRET'] %>

test:
  <<: *development