production: &production
  facebook:
    key: <%= ENV['FACEBOOK_KEY_PRODUCTION'] %>
    secret: <%= ENV['FACEBOOK_SECRET_PRODUCTION'] %>
  google:
    key: <%= ENV['GOOGLE_KEY_PRODUCTION'] %>
    secret: <%= ENV['GOOGLE_SECRET_PRODUCTION'] %>
  twitter:
    key: <%= ENV['TWITTER_KEY_PRODUCTION'] %>
    secret: <%= ENV['TWITTER_SECRET_PRODUCTION'] %>

development: &development
  <<: *production
  facebook:
    key: <%= ENV['FACEBOOK_KEY_DEVELOPMENT'] %>
    secret: <%= ENV['FACEBOOK_SECRET_DEVELOPMENT'] %>
  google:
    key: <%= ENV['GOOGLE_KEY_DEVELOPMENT'] %>
    secret: <%= ENV['GOOGLE_SECRET_DEVELOPMENT'] %>
  twitter:
    key: <%= ENV['TWITTER_KEY_DEVELOPMENT'] %>
    secret: <%= ENV['TWITTER_SECRET_DEVELOPMENT'] %>

test:
  <<: *development